package com.android.swingmusic.core.domain.model

data class TopResultItem(
    val id: Int,
    val type: String,
    val albumCount: Int,
    val artistHash: String,
    val albumHash: String,
    val trackHash: String,
    val genres: List<Genre>,
    val trackCount: Int,
    val albumcount: Int,
    val color: String,
    val createdDate: Int,
    val date: Int,
    val duration: Int,
    val favUserIds: List<String>,
    val genreHashes: String,
    val image: String,
    val lastPlayed: Int,
    val name: String,
    val playCount: Int,
    val playDuration: Int,
    val trackcount: Int,
    val album: String,
    val albumArtists: List<Artist>,
    val artistHashes: List<String>,
    val artists: List<Artist>,
    val bitrate: Int,
    val explicit: Boolean,
    val filepath: String,
    val folder: String,
    val isFavorite: Boolean,
    val title: String
)
